name: Build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Build package on ${{ matrix.dotnet-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x", "9.0.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build UsbBluetooth

      - name: Test
        run: dotnet test

      - name: Package
        run: dotnet pack UsbBluetooth -o dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: usbbluetooth_csharp_${{ matrix.dotnet-version }}
          path: dist/

  publish:
    name: Publish to NuGet
    needs: [build]
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: nuget
      url: https://www.nuget.org/packages/UsbBluetooth/
    permissions:
      id-token: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v5
      with:
        name: usbbluetooth_csharp_9.0.x
        path: dist/

    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: NuGet push
      run: dotnet nuget push dist/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
